# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/frontend

- name: Delete frontend container
  community.docker.docker_container:
    name: todolist-frontend
    state: absent
    force_kill: true

- name: Copy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /tmp/nginx.conf
    mode: '0644'

- name: Run frontend container —Å Nginx
  community.docker.docker_container:
    name: todolist-frontend
    image: "{{ frontend_image | default('todolist-frontend:latest') }}"
    restart_policy: always
    published_ports:
      - "80:80"
    volumes:
      - /tmp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    state: started
    pull: true
