version: "3.9"

services:
  backend:
    build:
      context: ./todo_api
    ports:
      - "8000:8000"
    volumes:
      - ./todo_api:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todo

  frontend:
    build:
      context: ./todo_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
