#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/db — без docker-compose, с гарантированной загрузкой образа с Docker Hub

- name: Run postgres container
  docker_container:
    name: todolist-db
    image: deniskostin/postgres:15
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
